services:
  api:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    profiles: [prod]

  workers:
    build: ./server
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - REDIS_URL=redis://redis:6379/0
    command: rq worker ingestion_queue --url redis://redis:6379/0
    deploy:
      replicas: 3
    profiles: [prod]

  rq-dashboard:
    build: ./server
    ports:
      - "9181:9181"
    depends_on:
      - redis
    command: rq-dashboard --redis-url redis://redis:6379/0 --port 9181
    profiles: [prod]

  redis:
    image: redis:8.6.1-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  mongo:
    image: mongo:8.2.6-rc0-noble
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
