POST http://localhost:8000/events
Content-Type: application/json

{
  // "type": "click",
  "timestamp": 1234567890,
  "user_id": "e4b75896-9354-4bd2-a15a-fdb20b20e802",
  "source_url": "http://example.com",
  "metadata": {
    "key": "value"
  }
}